version: '1.0'
name: fetch
displayName: fetch
triggers:
  trigger: auto
  schedule:
    - cron: '* 0 */3 * * ? *'
stages:
  - name: install_deps
    displayName: installdeps
    strategy: naturally
    trigger: auto
    executor:
      - dream-deve
    steps:
      - step: build@nodejs
        name: npm_install
        displayName: deps_install
        nodeVersion: 21.5.0
        commands:
          - npm config set registry https://registry.npmmirror.com
          - npm install
          - node fetchURLByWasm.js
          - git config user.name "Gitee流水线"
          - git config user.email "actions@githee.com"
          - git add .
          - git diff --quiet && git diff --staged --quiet || git commit -m "Update by Gitee流水线"
          - git push
        strategy:
          retry: '0'
          timeout: 5
