version: '1.0'
name: fetch
displayName: fetch
triggers:
  trigger: auto
  schedule:
    - cron: '* 0 */3 * * ? *'
variables:
  global:
    - TOKEN
stages:
  - name: install_deps
    displayName: installdeps
    strategy: naturally
    trigger: auto
    executor:
      - dream-deve
    steps:
      - step: build@nodejs
        name: fetchurl
        displayName: fetchurl
        nodeVersion: 21.5.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - '# 执行编译命令 '
          - echo "测试" > interface.txt.bak
          - cat interface.txt.bak
          - git config user.name "Gitee流水线"
          - git config user.email "actions@githee.com"
          - git add .
          - git diff --quiet && git diff --staged --quiet || git commit -m "Update by Gitee流水线"
          - git remote set-url origin https://dream-deve:${TOKEN}@gitee.com/dream-deve/migu_video.git
          - git push -u origin main
        caches: []
        notify: []
        strategy:
          retry: '0'
          timeout: 2
