version: '1.0'
name: pipeline-20240822
displayName: pipeline-20240822
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
  schedule:
    - cron: '* 45 11 * * ? *'
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands:
          - echo "hello world"
